### ISSUE TITLE
404 page not found on my metrics server webpage

### ISSUE THREAD

**Issue by Clingto** [google/buzzer#44]
Hi!
I've had buzzer running for 10+ hours and my metrics server shows no information (i.e., 404 page not found). 
I compiled my kernel with `kcov` and `kasan` as the syzkaller instructions, and built the `bullseye` image, 
and replace the `PATH_TO_DEBIAN_IMAGE` and `PATH_TO_KERNEL_REPO` with absolute path like  `/home/xxx/workspace/image/` and `/home/xxx/workspace/kernel/`, and my kernel build  `.config` includes: 
"CONFIG_BPF=y
CONFIG_BPF_SYSCALL=y
CONFIG_KCOV=y
CONFIG_KASAN=y"

I'm not sure where the problem is. It might be similar to [issue/37](https://github.com/google/buzzer/issues/37), but I haven't understood the solution. Please provide some assistance. Thank you.

**Comment by irving-11** [comment]
Try to visit http://localhost:8080/general .

**Comment by thatjiaozi** [comment]
yes! the handle that shows the statistics is in /general, not in /

**Comment by Clingto** [comment]
Yes, problem solved, thanks.
