### ISSUE TITLE
buzzer always raises error "Bad address"

### ISSUE THREAD

**Issue by m0ck1ng** [google/buzzer#5]
It is an excellent work. But I came accross some trouble when using Buzzer.
I successfully compiled and installed Buzzer according to the REAME.
However, it kept rasing error "Bad address" when executing eBPF prog.

My environment: OS 20.04, gcc-10

I configured Buzzer with the default settings and made sure that the BPF syscall is accessible as BCC worked fine.

Do you have any idea?

**Comment by thatjiaozi** [comment]
thanks for reaching out, can you share any logs/stderr with us?

**Comment by thatjiaozi** [comment]
Thanks! that sounds like most likely the ffi layer is not being able to create the sockets that the ebpf attaches the programs to: https://github.com/google/buzzer/blob/main/ebpf_ffi/ffi.cc#L208

I don't have access to a vm with your os version at the moment but I could take a closer look at the end of the day. 

If you happen to find the issue before feel free to send a pull request solving it :)

**Comment by m0ck1ng** [comment]
Thanks for patience! But I found that the error was triggered by
[https://github.com/google/buzzer/blob/4e7012f4b9fac7b306f74e0a54b3023f4fc6c867/ebpf_ffi/ffi.cc#L239](https://github.com/google/buzzer/blob/4e7012f4b9fac7b306f74e0a54b3023f4fc6c867/ebpf_ffi/ffi.cc#L239) and `errno` was exactly "error_message:'Bad address'".

Are the programs produced by Buzzer always valid? It seemed that the program was rejected by the kernel.

**Comment by thatjiaozi** [comment]
that is quite quite interesting.

If a program makes it to this stage it means that the verifier believes the program is valid. I have never seen the kernel reject a program at this stage :thinking: 

What could be happening is that for some reason the programs are not storing the right number of elements (?) but I am not 100% sure. 

Do you mind also running with the flag `--fuzzing_strategy=pointer_arithmetic` and see if it produces the same error?

**Comment by m0ck1ng** [comment]
Hi, could you tell me your compile-toolchains?

I compiled buzzer originally and got the following log:
```
root@4c2a28f96899:/home/buzzer# bazel build :buzzer
...
ebpf_ffi/ffi.cc: In function 'bpf_result execute_bpf_program(int, int, int)':
ebpf_ffi/ffi.cc:237:79: error: too many initializers for 'bpf_attr'
  237 |                                  .value = reinterpret_cast<uint64_t>(&element)};
      |                                                                               ^
Target //:buzzer failed to build
...
```
so I made some modification and successfully compiled buzzer.
```
    // original
    union bpf_attr lookup_map = {.map_fd = static_cast<uint32_t>(map_fd),
                                 .key = reinterpret_cast<uint64_t>(&key),
                                 .value = reinterpret_cast<uint64_t>(&element)};
    // modified
    union bpf_attr lookup_map = {static_cast<uint32_t>(map_fd),
                                 reinterpret_cast<uint64_t>(&key),
                                 reinterpret_cast<uint64_t>(&element)};
```
I think the modification may lead to the issue. I will be glad if more compile-toolchains information is offered.

**Comment by m0ck1ng** [comment]
I fixed the issue after using clang-12 instead of gcc-10. Thanks!😊

**Comment by thatjiaozi** [comment]
uh interesting that is good to know! the bpf structs change from one version of the toolchains to another, so it makes sense that using a different compiler solved the issue.

Please let us know if you find any more issues. Are we good to close this one?

**Comment by m0ck1ng** [comment]
Thanks for help. Feel free to close the issue.
